In [2]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)


int32


In [3]:
#2. Given a NumPy array 'arr', check if its data type is float64.arr = np.array([1.5, 2.6, 3.7])
arr = np.array([1.5,2.6,3.7])
print(arr.dtype)

float64


In [4]:
#2. Given a NumPy array 'arr', check if its data type is float64.arr = np.array([1.5, 2.6, 3.7])

arr = np.array([1.5, 2.6, 3.7])

if arr.dtype == np.float64:
    print("The data type of arr is float64.")
else:
    print("The data type of arr is not float64.")


The data type of arr is float64.


In [4]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex128)
print(arr)


[1.+2.j 3.+4.j 5.+6.j]


In [5]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.

# Assuming arr is your existing NumPy array of integers
arr = np.array([1, 2, 3, 4, 5])

# Convert arr to float32 data type
arr = arr.astype(np.float32)

print(arr)


[1. 2. 3. 4. 5.]


In [6]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

# Assuming arr is your existing NumPy array of float64
arr = np.array([1.123456789, 2.234567891, 3.345678912], dtype=np.float64)

# Convert arr to float32 data type
arr = arr.astype(np.float32)

print(arr)


[1.1234568 2.2345679 3.3456788]


In [7]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    data_type = arr.dtype
    return shape, size, data_type

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
attributes = array_attributes(arr)
print("Shape:", attributes[0])
print("Size:", attributes[1])
print("Data type:", attributes[2])


Shape: (2, 3)
Size: 6
Data type: int64


In [8]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

def array_dimension(arr):
    return arr.ndim

# Example usage:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

print("Dimension of arr1:", array_dimension(arr1))
print("Dimension of arr2:", array_dimension(arr2))


Dimension of arr1: 2
Dimension of arr2: 1


In [9]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.size * arr.itemsize
    return item_size, total_size

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(arr)
print("Item size (in bytes):", item_size)
print("Total size (in bytes):", total_size)


Item size (in bytes): 8
Total size (in bytes): 48


In [10]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(arr):
    return arr.strides

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print("Strides:", strides)


Strides: (24, 8)


In [11]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

def shape_stride_relationship(arr):
    return arr.shape
    return arr.strides
# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape = shape_stride_relationship(arr)
strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (2, 3)


In [12]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

def shape_stride_relationship(arr):
    return arr.shape, arr.strides

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)


Shape: (2, 3)
Strides: (24, 8)


In [13]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(arr):
    return np.zeros(n)

# Example usage:
n = 5
zeros_array = create_zeros_array(n)
print(zeros_array)


[0. 0. 0. 0. 0.]


In [14]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x co

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

# Example usage:
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified step

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# Example usage:
start = 0
stop = 10
step = 2
result = generate_range_array(start, stop, step)
print(result)


[0 2 4 6 8]


In [ ]:
#Q14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [10]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)


#Example usage:
start = 0.0
stop = 10.0
num = 5
result = generate_linear_space(start, stop, num)
print(result)

[ 0.   2.5  5.   7.5 10. ]


In [7]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye

def create_identity_matrix(n):
    return np.eye(n)

#Example usage:
n = 4
result = create_identity_matrix(n)
print(result)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
#16. Write a function that takes a Python list and converts it into a NumPy array.

def list_to_numpy_array(list):
    return np.array(list)


#Example usage:
list = [1,2,4,5,7,]
result = list_to_numpy_array(list)
print(result)

[1 2 4 5 7]


In [19]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Use numpy.view to create a new array object with the same data
view_array = original_array.view()

# Modify the view_array
view_array[0] = 10

# Display both arrays
print("Original array:", original_array)
print("View array:", view_array)


Original array: [10  2  3  4  5]
View array: [10  2  3  4  5]


In [18]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Concatenate along axis 0 (rows)
result_axis_0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:")
print(result_axis_0)




Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]]


In [21]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate.
import numpy as np
# Create two NumPy arrays with different shapes
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8],
                   [9, 10]])

# Concatenate them horizontally
result = np.concatenate((array1, array2), axis=1)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nConcatenated Array:")
print(result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8]
 [ 9 10]]

Concatenated Array:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [22]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate.
import numpy as np
# Create two NumPy arrays with different shapes
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8],
                   [9, 10]])

# Concatenate them horizontally
result = np.concatenate((array1, array2), axis=1)

print(result)


[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [23]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.


import numpy as np

def vertical_stack(arrays):
    stacked_array = np.vstack(arrays)
    return stacked_array

# Example usage:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

array3 = np.array([[13, 14, 15],
                   [16, 17, 18]])

stacked_result = vertical_stack([array1, array2, array3])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nArray 3:")
print(array3)
print("\nVertically Stacked Result:")
print(stacked_result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Array 3:
[[13 14 15]
 [16 17 18]]

Vertically Stacked Result:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [24]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size

import numpy as np

def create_integer_array(start, stop, step):
    int_array = np.arange(start, stop + 1, step)
    return int_array

# Example usage:
start = 0
stop = 10
step = 2

result_array = create_integer_array(start, stop, step)
print("Array of integers within the range [{}, {}] with step {}: {}".format(start, stop, step, result_array))


Array of integers within the range [0, 10] with step 2: [ 0  2  4  6  8 10]


In [25]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive)

def generate_array():
    return np.linspace(0, 1, 10)

# Test the function
result = generate_array()
print(result)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [20]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def generate_log_array():
    return np.logspace(0,3,5)

result = generate_log_array()
print(result)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [27]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

import pandas as pd

# Generate a NumPy array with random integers
random_array = np.random.randint(1, 101, size=(5, 3))

# Create a DataFrame using the NumPy array
df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])

# Display the DataFrame
print(df)




   Column1  Column2  Column3
0        8       11       36
1       54       33       29
2       38       94       32
3       11       83        7
4       60       82       31


In [28]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame

def replace_negatives_with_zeros(df, column_name):
    for index, value in enumerate(df[column_name]):
        if value < 0:
            df.at[index, column_name] = 0
    return df

# Test the function
# Create a sample DataFrame
data = {'A': [1, 2, -3, 4, -5],
        'B': [-1, 2, 3, -4, 5],
        'C': [1, -2, 3, -4, 5]}
df = pd.DataFrame(data)

# Replace negative values in column 'B' with zeros
modified_df = replace_negatives_with_zeros(df, 'B')

print("Original DataFrame:")
print(df)
print("\nDataFrame after replacing negative values in column 'B' with zeros:")
print(modified_df)


Original DataFrame:
   A  B  C
0  1  0  1
1  2  2 -2
2 -3  3  3
3  4  0 -4
4 -5  5  5

DataFrame after replacing negative values in column 'B' with zeros:
   A  B  C
0  1  0  1
1  2  2 -2
2 -3  3  3
3  4  0 -4
4 -5  5  5


In [29]:
'''26. Access the 3rd element from the given NumPy array
 arr = np.array([10, 20, 30, 40, 50])'''

arr = np.array([10, 20, 30, 40, 50])
Third_element = arr[2]
print(Third_element)


30


In [30]:
'''27. Retrieve the element at index (1, 2) from the 2D NumPy array
        arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]) '''
import numpy as np

# Access the element at index (1, 2)
element_12 = arr_2d[1, 2]

print("Element at index (1, 2) of the array:", element_12)



Element at index (1, 2) of the array: 6


In [32]:
#Q28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

        arr = np.array([3, 8, 2, 10, 5, 7])

import numpy as np

# Access the element at boolean indexing which is greater than 5
arr = np.array([3, 8, 2, 10, 5, 7])
result = arr[arr > 5]

result

array([ 8, 10,  7])

In [29]:
#29 Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
'''arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) '''

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_arr = arr[2:6]  # indices 2, 3, 4, 5
print(sliced_arr)


[3 4 5 6]


In [34]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

'''arr_2d = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])'''


sliced_arr_2d = arr_2d[0:2, 1:3]  # rows 0 to 1 and columns 1 to 2
print(sliced_arr_2d)


[[2 3]
 [5 6]]


In [41]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another arra

# Example usage
def extract_elements(arr_2d, indices):
     arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([0, 4, 8])  # Example indices (flat index)

extracted_elements = extract_elements(arr_2d, indices)
print(extracted_elements)



None


In [36]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

import numpy as np

def filter_greater_than_threshold(arr, threshold):
    """
    Filters elements greater than a given threshold from a 1D array.

    Parameters:
    arr (numpy.ndarray): Input 1D array.
    threshold (float): Threshold value.

    Returns:
    numpy.ndarray: Array containing elements greater than the threshold.
    """
    # Ensure the input is a numpy array
    arr = np.asarray(arr)
    # Use boolean indexing to filter elements
    filtered_array = arr[arr > threshold]
    return filtered_array

# Example usage:
array = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8, 10])
threshold = 5
filtered_array = filter_greater_than_threshold(array, threshold)
print(filtered_array)


[ 7  9  6  8 10]


In [37]:
# 33.  Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

import numpy as np

def extract_elements_3d(arr, indices_x, indices_y, indices_z):
    """
    Extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

    Parameters:
    arr (numpy.ndarray): Input 3D array.
    indices_x (numpy.ndarray): Array of indices for the first dimension.
    indices_y (numpy.ndarray): Array of indices for the second dimension.
    indices_z (numpy.ndarray): Array of indices for the third dimension.

    Returns:
    numpy.ndarray: Array containing the extracted elements.
    """
    # Ensure the input arrays are numpy arrays
    indices_x = np.asarray(indices_x)
    indices_y = np.asarray(indices_y)
    indices_z = np.asarray(indices_z)

    # Use advanced indexing to extract the elements
    extracted_elements = arr[indices_x, indices_y, indices_z]

    return extracted_elements

# Example usage:
array_3d = np.random.randint(0, 100, (5, 5, 5))
indices_x = np.array([0, 1, 2])
indices_y = np.array([1, 2, 3])
indices_z = np.array([2, 3, 4])

extracted_elements = extract_elements_3d(array_3d, indices_x, indices_y, indices_z)
print("3D Array:\n", array_3d)
print("Extracted Elements:\n", extracted_elements)


3D Array:
 [[[68 83 99 39 11]
  [26  5 64 31 25]
  [ 0 43 69 62 74]
  [58 38 79 18 84]
  [74 42 52 57 84]]

 [[54 37  3  3 86]
  [16 73 35 72 25]
  [58 33  3 18 34]
  [ 1 94 62 96 49]
  [ 5  1 23  3 37]]

 [[95  1 61 63 14]
  [75 27 63 10 48]
  [99 68 89 10 45]
  [ 4 31 92 42 48]
  [45  2 43 75 35]]

 [[80  0 41 47 94]
  [52 73  1 69 88]
  [37 25 78 60 87]
  [55 13 13 43 34]
  [53 20  5 32 72]]

 [[92 92 80 90 61]
  [47 95 70 82 76]
  [42  4 10 95 56]
  [17 99 45 94 40]
  [48 70 13 84 93]]]
Extracted Elements:
 [64 18 48]


In [6]:
# 34.  Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

import numpy as np

def filter_array(arr, condition1, condition2):
    """
    Filters an array based on two conditions using boolean indexing.

    Args:
        arr: The NumPy array to filter.
        condition1: The first condition to apply (e.g., arr > 5).
        condition2: The second condition to apply (e.g., arr < 10).

    Returns:
        A NumPy array containing elements that satisfy both conditions.
    """

    mask = condition1 & condition2
    return arr[mask]


In [39]:
# 35.  Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.


import numpy as np

def extract_elements_2d(arr, row_indices, col_indices):
    """
    Extracts specific elements from a 2D array using row and column indices provided in separate arrays.

    Parameters:
    arr (numpy.ndarray): Input 2D array.
    row_indices (list or numpy.ndarray): List or array of row indices.
    col_indices (list or numpy.ndarray): List or array of column indices.

    Returns:
    numpy.ndarray: Array containing the extracted elements.
    """
    # Convert indices to numpy arrays if they aren't already
    row_indices = np.array(row_indices)
    col_indices = np.array(col_indices)

    # Extract elements using the provided indices
    extracted_elements = arr[row_indices, col_indices]

    return extracted_elements

# Example usage:
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

row_indices = [0, 1, 2]
col_indices = [1, 0, 2]

extracted_elements = extract_elements_2d(array_2d, row_indices, col_indices)
print("2D Array:\n", array_2d)
print("Extracted Elements:\n", extracted_elements)


2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Extracted Elements:
 [20 40 90]


In [40]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

import numpy as np

# Given array of shape (3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a scalar value of 5 to each element
arr_plus_5 = arr + 5

# Print the resulting array
print("Original Array:\n", arr)
print("Array after adding 5:\n", arr_plus_5)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after adding 5:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [41]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

import numpy as np

# Given arrays
arr1 = np.array([[2, 3, 4]])  # shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # shape (3, 4)

# Multiply each row of arr2 by the corresponding element in arr1
result = arr2 * arr1.T

# Print the resulting array
print("Array arr1:\n", arr1)
print("Array arr2:\n", arr2)
print("Resulting array after broadcasting and multiplying:\n", result)


Array arr1:
 [[2 3 4]]
Array arr2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Resulting array after broadcasting and multiplying:
 [[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [42]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting

import numpy as np

# Given arrays
arr1 = np.array([1, 2, 3, 4])  # shape (4,)
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])  # shape (4, 3)

# Reshape arr1 to (1, 4) to allow broadcasting across arr2
arr1_reshaped = arr1.reshape(4, 1)

# Add arr1 to each row of arr2
result = arr1_reshaped + arr2

# Print the resulting array
print("Array arr1:\n", arr1)
print("Array arr2:\n", arr2)
print("Resulting array after broadcasting and adding:\n", result)



Array arr1:
 [1 2 3 4]
Array arr2:
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Resulting array after broadcasting and adding:
 [[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [43]:
#39.  Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

import numpy as np

# Create arr1 of shape (3, 1)
arr1 = np.array([[1], [2], [3]])

# Create arr2 of shape (1, 3)
arr2 = np.array([[4, 5, 6]])

# Add arr1 and arr2
result = arr1 + arr2

# Print the result
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [44]:
# 40. given arrays arr1 of shape(3,1) and arr2 of shape(2,2) perform multiplication using numpy broading handle the shape incompatibility.
import numpy as np

# Create arr1 of shape (2, 3)
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

# Create arr2 of shape (2, 2)
arr2 = np.array([[1, 2], [3, 4]])

# Expand arr2 to match the shape of arr1
arr2_expanded = np.array([[arr2[0,0], arr2[0,1], arr2[0,0]], [arr2[1,0], arr2[1,1], arr2[1,0]]])

print("Expanded arr2:")
print(arr2_expanded)

# Perform element-wise multiplication
result = arr1 * arr2_expanded

# Print the result
print("Result:")
print(result)


Expanded arr2:
[[1 2 1]
 [3 4 3]]
Result:
[[ 1  4  3]
 [12 20 18]]


In [45]:
#41. Calculate column wise mean for the given array:
''' arr = np.array([[1, 2, 3], [4, 5, 6]])'''

import numpy as np

# Define the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Calculate column-wise mean
column_wise_mean = np.mean(arr, axis=0)

# Print the result
print("Column-wise mean:\n", column_wise_mean)



Column-wise mean:
 [2.5 3.5 4.5]


In [47]:
# 42.  Find maximum value in each row of the given array:
'''arr = np.array([[1, 2, 3], [4, 5, 6]])'''

# Define the array

arr = np.array([[1, 2, 3], [4, 5, 6]])

#Max value in row

max_value = np.max(arr, axis = 1)

#Print the result
print("Maximum value in each row:\n", max_value)


Maximum value in each row:
 [3 6]


In [48]:
#43.  For the given array, find indices of maximum value in each column.
''' arr = np.array([[1, 2, 3], [4, 5, 6]]) '''

#Define the array

arr = np.array([[1, 2, 3], [4, 5, 6]])

#Indices of the max values

col_max_indices = np.argmax(arr,axis = 0)

#Print the Result
print("Indices of Maximum value:\n",col_max_indices)


Indices of Maximum value:
 [1 1 1]


In [49]:
# 44.  For the given array, apply custom function to calculate moving sum along rows.
'''arr = np.array([[1, 2, 3], [4, 5, 6]])'''

import numpy as np

# Define the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Define a simple function for the moving sum
def moving_sum(row):
    result = []
    for i in range(len(row) - 1):
        result.append(row[i] + row[i + 1])
    return result

# Apply the moving sum function to each row
result = np.array([moving_sum(row) for row in arr])

# Print the result
print("Moving sum along rows:")
print(result)


Moving sum along rows:
[[ 3  5]
 [ 9 11]]


In [50]:
# 45. . In the given array, check if all elements in each column are even.
'''arr = np.array([[2, 4, 6], [3, 5, 7]])'''

# Define the array
arr = np.array([[2, 4, 6], [3, 5, 7]])

# Check if each element is even
is_even = (arr % 2 == 0)
print("Array of even checks:\n", is_even)

# Check if all elements in each column are even
all_even_columns = np.all(is_even, axis=0)

# Print the result
print("Are all elements in each column even:\n", all_even_columns)



Array of even checks:
 [[ True  True  True]
 [False False False]]
Are all elements in each column even:
 [False False False]


In [51]:
#46.  Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
'''original_array = np.array([1, 2, 3, 4, 5, 6])'''

import numpy as np

# Define the original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Define the target dimensions
m = 2
n = 3

# Reshape the array
reshaped_matrix = original_array.reshape(m, n)

# Print the result
print("Reshaped matrix:\n",reshaped_matrix)





Reshaped matrix:
 [[1 2 3]
 [4 5 6]]


In [52]:
#47.  Create a function that takes a matrix as input and returns the flattened array
'''input_matrix = np.array([[1, 2, 3], [4, 5, 6]])'''

import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)



[1 2 3 4 5 6]


In [53]:
#48.  Write a function that concatenates two given arrays along a specified axis.
'''array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])'''

import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Example: Concatenate along axis 0
concatenated_axis_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concatenated_axis_0)

# Example: Concatenate along axis 1
concatenated_axis_1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", concatenated_axis_1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [54]:
#49.  Create a function that splits an array into multiple sub-arrays along a specified axis.
'''original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])'''

import numpy as np

def split_array(array, indices_or_sections, axis=0):
    return np.split(array, indices_or_sections, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Example: Split along axis 0 into 3 equal parts
split_axis_0 = split_array(original_array, 3, axis=0)
print("Split along axis 0 into 3 parts:\n", split_axis_0)

# Example: Split along axis 1 into 3 equal parts
split_axis_1 = split_array(original_array, 3, axis=1)
print("Split along axis 1 into 3 parts:\n", split_axis_1)



Split along axis 0 into 3 parts:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Split along axis 1 into 3 parts:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [56]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
'''original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]'''


import numpy as np

def insert_and_delete_elements(array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    array = np.insert(array, indices_to_insert, values_to_insert)

    # Adjust the indices for deletion after insertion
    adjusted_indices_to_delete = [index + sum(i < index for i in indices_to_insert) for index in indices_to_delete]

    # Delete elements at specified indices
    array = np.delete(array, adjusted_indices_to_delete)

    return array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Resulting array:", result_array)


Resulting array: [ 1 10  3 11  5]


In [57]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
'''original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]'''


import numpy as np

def insert_and_delete_elements(array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    array = np.insert(array, indices_to_insert, values_to_insert)

    # Adjust the indices for deletion after insertion
    adjusted_indices_to_delete = [index + sum(i < index for i in indices_to_insert) for index in indices_to_delete]

    # Delete elements at specified indices
    array = np.delete(array, adjusted_indices_to_delete)

    return array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Resulting array:", result_array)


Resulting array: [ 1 10  3 11  5]


In [58]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
'''original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]'''


import numpy as np

def insert_and_delete_elements(array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    array = np.insert(array, indices_to_insert, values_to_insert)

    # Adjust the indices for deletion after insertion
    adjusted_indices_to_delete = [index + sum(i < index for i in indices_to_insert) for index in indices_to_delete]

    # Delete elements at specified indices
    array = np.delete(array, adjusted_indices_to_delete)

    return array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Resulting array:", result_array)


Resulting array: [ 1 10  3 11  5]


In [59]:
#51.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.Perform element-wise addition between `arr1` and `arr2`.

import numpy as np

# Create a NumPy array `arr1` with random integers
arr1 = np.random.randint(0, 10, size=10)

# Create another array `arr2` with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise addition between `arr1` and `arr2`
result_array = np.add(arr1, arr2)

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise addition:", result_array)


arr1: [5 8 8 0 6 8 9 2 3 1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise addition: [ 6 10 11  4 11 14 16 10 12 11]


In [60]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

import numpy as np

# Create a NumPy array `arr1` with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Create another array `arr2` with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise subtraction of `arr2` from `arr1`
result_array = np.subtract(arr1, arr2)

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise subtraction:", result_array)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise subtraction: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [61]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.Perform element-wise multiplication between `arr1` and `arr2`.

#Create a NumPy array `arr1` with random integers
arr1 = np.random.randint(0, 10, size=5)

# Create another array `arr2` with integers from 1 to 5
arr2 = np.arange(1, 6)

#Perform element-wise multiplication between `arr1` and `arr2`.
result_array = np.multiply(arr1,arr2)

print("arr1:", arr1)
print("arr2:" ,arr2)
print("Result of element wise multiplication:" ,result_array)


arr1: [2 2 2 8 8]
arr2: [1 2 3 4 5]
Result of element wise multiplication: [ 2  4  6 32 40]


In [62]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

#create a numpy array 'arr1' with even integers from 2 to 10
arr1 = np.arange(2,11,2)

#create a numpy array 'arr2' with integer from 1 to 5
arr2 = np.arange(1,6)

# Perform element-wise division of `arr1` by `arr2`.
result_array = np.divide(arr1,arr2)

print("arr1:",arr1)
print("arr2:",arr2)
print("Result of the element-wise division.",result_array)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Result of the element-wise division. [2. 2. 2. 2. 2.]


In [63]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.


# Create a NumPy array `arr1` with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create another array `arr2` with integers from 1 to 5 reversed
arr2 = np.arange(5, 0, -1)

# Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise
result_array = np.power(arr1, arr2)

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise exponentiation:", result_array)


arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Result of element-wise exponentiation: [ 1 16 27 16  5]


In [64]:
#6. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
'''arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])'''

import numpy as np

def count_substring_occurrences(arr, substring):
    # Use a list comprehension to count occurrences of the substring in each string
    count = sum(s.count(substring) for s in arr)
    return count

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

# Count the occurrences of 'hello'
occurrences = count_substring_occurrences(arr, substring)
print(f"Occurrences of '{substring}':", occurrences)



Occurrences of 'hello': 3


In [65]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings. arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
'''arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])'''



def extract_uppercase(arr):
    # This list will store the uppercase characters for each string
    result = []

    # Loop through each string in the array
    for string in arr:
        # Create a new string to hold only the uppercase characters
        uppercase_chars = ''
        # Loop through each character in the string
        for char in string:
            # Check if the character is uppercase
            if char.isupper():
                # Add the uppercase character to our new string
                uppercase_chars += char
        # Append the result for this string to our list
        result.append(uppercase_chars)

    # Convert the list to a NumPy array and return it
    return np.array(result)

# Create a NumPy array of strings
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Call the function and get the uppercase characters
uppercase_result = extract_uppercase(arr)

# Print the result
print("Uppercase characters extracted:", uppercase_result)


Uppercase characters extracted: ['H' 'W' 'OAI' 'GPT']


In [66]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
'''arr = np.array(['apple', 'banana', 'grape', 'pineapple'])'''
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    # This list will store the modified strings
    result = []

    # Loop through each string in the array
    for string in arr:
        # Replace the old substring with the new substring
        modified_string = string.replace(old_substring, new_substring)
        # Append the modified string to our list
        result.append(modified_string)

    # Convert the list to a NumPy array and return it
    return np.array(result)

# Create a NumPy array of strings
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Define the old substring to replace and the new substring
old_substring = 'apple'
new_substring = 'orange'

# Call the function and get the modified array
modified_array = replace_substring(arr, old_substring, new_substring)

# Print the result
print("Modified array:", modified_array)



Modified array: ['orange' 'banana' 'grape' 'pineorange']


In [67]:
#59. Write a function that concatenates strings in a NumPy array element-wise.
'''arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])'''

def concatenate_strings(arr1, arr2):
    # Use numpy's vectorized operation to concatenate strings element-wise
    return np.char.add(arr1, arr2)

# Create two NumPy arrays of strings
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Call the function to concatenate the arrays element-wise
concatenated_array = concatenate_strings(arr1, arr2)

# Print the result
print("Concatenated array:", concatenated_array)


Concatenated array: ['HelloOpen' 'WorldAI']


In [68]:
#60. Write a function that finds the length of the longest string in a NumPy array. arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
'''arr = np.array(['apple', 'banana', 'grape', 'pineapple'])'''

import numpy as np

def find_longest_string_length(arr):
    # Initialize the maximum length to zero
    max_length = 0

    # Loop through each string in the array
    for string in arr:
        # Calculate the length of the current string
        length = len(string)
        # Update the maximum length if the current length is greater
        if length > max_length:
            max_length = length

    # Return the maximum length found
    return max_length

# Create a NumPy array of strings
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Call the function to find the length of the longest string
longest_length = find_longest_string_length(arr)

# Print the result
print("Length of the longest string:", longest_length)


Length of the longest string: 9


In [69]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

# Step 1: Generate a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1,1001,size = 100)

# Step 2: Compute the mean
mean_value = np.mean(dataset)

# Step 3: Compute the median
median_value = np.median(dataset)

# Step 4: Compute the variance
variance_value = np.var(dataset)

# Step 5: Compute the standard deviation
standard_deviation_value = np.std(dataset)

print("Dataset:",dataset)
print("Mean:",mean_value)
print("Median:",median_value)
print("Variance:",variance_value)
print("Standard Deviation:",standard_deviation_value)

Dataset: [757 857 721 877 481  86 401 643 712  94 281 853 408 448 299 733 861 414
 614 359 681 769 371 501 983 109 685 691 732  99 132 552 906 307 436 859
 259 296 790 984 614 657 806 578 987 566 395 460 619 876 727 133 525 589
 444 335 270 534 467 877  45 425  80 402 726 158 932 953  11 266 774 518
  98 362 940 738   6 310 526 708  66 776 759  85 538 167 785 335 878 253
 538 571 474 941 692 719 270 414 348 586]
Mean: 526.73
Median: 536.0
Variance: 72163.3571
Standard Deviation: 268.63238282083563


In [72]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset


import numpy as np

#Generate the 50 random numbers
random_numbers = np.random.randint(1,101,50)

#25th and 75th percentilte of the dataset

percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)

print("25th percentile:",percentile_25)
print("75th percentile:",percentile_75)

25th percentile: 12.0
75th percentile: 58.75


In [73]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function

import numpy as np

# Create two arrays representing two sets of variables
array1 = np.random.randint(1, 101, size=50)
array2 = np.random.randint(1, 101, size=50)

# Compute the correlation coefficient between these arrays
correlation_matrix = np.corrcoef(array1, array2)
correlation_coefficient = correlation_matrix[0, 1]

array1, array2, correlation_coefficient


(array([24, 75, 37, 44, 14, 95, 29, 76, 83, 31, 74, 11, 61, 30, 57,  2, 81,
        37, 83, 50, 54, 46, 60, 90, 24, 20, 89,  1,  4, 43, 14, 67, 93, 53,
         1, 31, 89, 26, 34, 91, 83, 55, 17, 77, 67, 91, 96, 15, 94, 71]),
 array([78, 73, 79,  4,  4, 20,  7, 77, 81, 46, 40, 98, 58, 88, 97, 19, 46,
        26, 78, 53, 84, 53,  3, 91, 98, 49, 24, 57, 42, 70, 82, 31, 59, 40,
        34,  1, 96, 99, 17, 75, 44, 45, 91, 11, 36, 86, 72, 32, 46,  6]),
 0.07780819636975261)

In [74]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

import numpy as np

#create two matrices

matrix1 = np.random.randint(1,101,size = (3, 4))
matrix2 = np.random.randint(1,101, size = (4,3))

#matrix multiplication using "dot" function

result = np.dot(matrix1, matrix2)

print('Matrix 1:',matrix1)
print("Matrix 2:", matrix2)
print("RESULT:", result)


Matrix 1: [[22 93 98 17]
 [82 39 76 21]
 [52 89 96 54]]
Matrix 2: [[ 61  13  75]
 [100  93  84]
 [ 35  36  98]
 [ 65  11  53]]
RESULT: [[15177 12650 19967]
 [12927  7660 17987]
 [18942 13003 23646]]


In [75]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

import numpy as np

#create an array
array = np.random.randint(10,1001,50)

#calculate the percentile

percentile_10 = np.percentile(array,10)
percentile_50 = np.percentile(array,50)
percentile_90 = np.percentile(array,90)

#calculate the first and the third quartile
percentile_25 = np.percentile(array,25)
percentile_75 = np.percentile(array,75)

print("10th Percentile:",percentile_10)
print("50th Percentile:",percentile_50)
print("90th Percentile:",percentile_90)
print("First Quartile:",percentile_25)
print("Third Quartile:",percentile_75)





10th Percentile: 160.3
50th Percentile: 497.0
90th Percentile: 850.3
First Quartile: 264.25
Third Quartile: 680.5


In [76]:
# 66. Create a NumPy array of integers and find the index of a specific element.

#Create a NumPy array
array = np.array([10,20,55,67,49,80,60,40,100,120])

#Specific Element
element_to_find = 67

#Find the index of the specific element
index = np.where(array == element_to_find)

print("Array:",array)
print("Element Index:",index[0])

Array: [ 10  20  55  67  49  80  60  40 100 120]
Element Index: [3]


In [77]:
# 67. Generate a random NumPy array and sort it in ascending order.

#Create a random NumPy array
array = np.random.randint(1,100,10)

#Sort it in ascending order
ascending = np.sort(array)

print("Array:", array)
print("Sort in Ascending order:" , ascending)

Array: [23 91 55 84 61 99 59 43 23 10]
Sort in Ascending order: [10 23 23 43 55 59 61 84 91 99]


In [78]:
# 68. Filter elements >20  in the given NumPy array
'''arr = np.array([12, 25, 6, 42, 8, 30])'''

#Given array
arr = np.array([12, 25, 6, 42, 8, 30])

#Filter element greater than 20
filter_elements = arr[arr>20]

print("Filter Elements:",filter_elements)

Filter Elements: [25 42 30]


In [79]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
'''arr = np.array([1, 5, 8, 12, 15])'''

#Given array
arr = np.array([1, 5, 8, 12, 15])

#Filter elements divisible by 3
filter_elements = arr[arr % 3 == 0]
print("Filter Elements:",filter_elements)

Filter Elements: [12 15]


In [80]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
'''arr = np.array([10, 20, 30, 40, 50])'''

#Given array
arr = np.array([10, 20, 30, 40, 50])

#filter elements which are ≥ 20 and ≤ 40
filter_elements = arr[(arr >= 20)&(arr <= 40)]

print("Filter Elements:",filter_elements)

Filter Elements: [20 30 40]


In [2]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])

import numpy as np

#Given array
arr = np.array([1,2,3])

# Check the byte order using the dtype attribute
byte_order = arr.dtype.byteorder

print(f"Byte order: {byte_order}")


Byte order: =


In [82]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
'''arr = np.array([1, 2, 3], dtype=np.int32)'''
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(True)

# Print the byte-swapped array
print(arr)


[16777216 33554432 50331648]


In [83]:
#73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
'''arr = np.array([1, 2, 3], dtype=np.int32)'''

import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap the byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Print the original and byte-swapped arrays
print("Original array:", arr)
print("Byte-swapped array:", swapped_arr)


Original array: [1 2 3]
Byte-swapped array: [16777216 33554432 50331648]


In [84]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using` newbyteorder()
'''arr = np.array([1, 2, 3], dtype=np.int32)'''

import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's endianness
system_endianness = np.dtype(np.int32).byteorder

# Swap the byte order conditionally
if system_endianness == '=':  # Native byte order (little-endian on most systems)
    # Swap to big-endian if the system is little-endian
    swapped_arr = arr.newbyteorder('>')
else:
    # Swap to little-endian if the system is big-endian
    swapped_arr = arr.newbyteorder('<')

# Print the original and byte-swapped arrays
print("Original array:", arr)
print("Conditionally byte-swapped array:", swapped_arr)



Original array: [1 2 3]
Conditionally byte-swapped array: [16777216 33554432 50331648]


In [85]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
'''arr = np.array([1, 2, 3], dtype=np.int32)'''

import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's native byte order
system_byteorder = '='

# Check the byte order of the array
array_byteorder = arr.dtype.byteorder

# Determine if byte swapping is necessary
if array_byteorder in ('=', system_byteorder):
    byte_swapping_necessary = False
else:
    byte_swapping_necessary = True

# Print the result
print("Array byte order:", array_byteorder)
print("System byte order:", system_byteorder)
print("Is byte swapping necessary?", byte_swapping_necessary)



Array byte order: =
System byte order: =
Is byte swapping necessary? False


In [86]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

import numpy as np

# Create a NumPy array with values from 1 to 10
arr1 = np.array(range(1, 11))

# Create a copy of arr1
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Print both arrays to check if modifying copy_arr affects arr1
print("Original array (arr1):", arr1)
print("Modified copy (copy_arr):", copy_arr)


Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified copy (copy_arr): [100   2   3   4   5   6   7   8   9  10]


In [87]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

import numpy as np

# Create a 2D NumPy array of shape (3, 3) with random integers
matrix = np.random.randint(1, 101, size=(3, 3))

# Extract a slice from the matrix
view_slice = matrix[0:2, 0:2]  # Extracting the top-left 2x2 submatrix

# Print the original matrix and the view slice
print("Original matrix:")
print(matrix)
print("View slice before modification:")
print(view_slice)

# Modify an element in the view slice
view_slice[0, 0] = 999

# Print the original matrix and the view slice after modification
print("Modified view slice:")
print(view_slice)
print("Original matrix after modifying the view slice:")
print(matrix)


Original matrix:
[[67 39  7]
 [38 33 83]
 [66 80 66]]
View slice before modification:
[[67 39]
 [38 33]]
Modified view slice:
[[999  39]
 [ 38  33]]
Original matrix after modifying the view slice:
[[999  39   7]
 [ 38  33  83]
 [ 66  80  66]]


In [88]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

import numpy as np

# Create a NumPy array of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice from the array
view_b = array_a[1:3, :]  # Extracting the middle 2 rows

# Print the original array and the view slice before modification
print("Original array (array_a):")
print(array_a)
print("View slice before modification (view_b):")
print(view_b)

# Broadcast the addition of 5 to the view slice
view_b += 5

# Print the view slice and the original array after modification
print("View slice after modification (view_b):")
print(view_b)
print("Original array after modifying the view slice (array_a):")
print(array_a)


Original array (array_a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
View slice before modification (view_b):
[[4 5 6]
 [7 8 9]]
View slice after modification (view_b):
[[ 9 10 11]
 [12 13 14]]
Original array after modifying the view slice (array_a):
[[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [10 11 12]]


In [89]:
#79.Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

import numpy as np

# Create a NumPy array of shape (2, 4) with values from 1 to 8

orig_array = np.arange(1, 9).reshape(2, 4)
# Create a reshaped view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)

# Print the original array and the reshaped view before modification
print("Original array (orig_array):")
print(orig_array)
print("Reshaped view before modification (reshaped_view):")
print(reshaped_view)

# Modify an element in the reshaped view
reshaped_view[0, 0] = 999

# Print the reshaped view and the original array after modification
print("Reshaped view after modification (reshaped_view):")
print(reshaped_view)
print("Original array after modifying the reshaped view (orig_array):")
print(orig_array)




Original array (orig_array):
[[1 2 3 4]
 [5 6 7 8]]
Reshaped view before modification (reshaped_view):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Reshaped view after modification (reshaped_view):
[[999   2]
 [  3   4]
 [  5   6]
 [  7   8]]
Original array after modifying the reshaped view (orig_array):
[[999   2   3   4]
 [  5   6   7   8]]


In [90]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

import numpy as np

# Create a NumPy array of shape (3, 4) with random integers between 1 and 10
data = np.random.randint(1, 11, size=(3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Print the original array and the copied array before modification
print("Original array (data):")
print(data)
print("Copied array before modification (data_copy):")
print(data_copy)

# Modify an element in the copied array
if data_copy.size > 0:
    data_copy[0] = 999

# Print the copied array and the original array after modification
print("Copied array after modification (data_copy):")
print(data_copy)
print("Original array after modifying the copied array (data):")
print(data)


Original array (data):
[[ 5  9  1 10]
 [ 5  5  3  7]
 [ 4  2  8  4]]
Copied array before modification (data_copy):
[ 9 10  7  8]
Copied array after modification (data_copy):
[999  10   7   8]
Original array after modifying the copied array (data):
[[ 5  9  1 10]
 [ 5  5  3  7]
 [ 4  2  8  4]]


In [91]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

import numpy as np

# Create two matrices A and B of shape (3, 3) with random integers between 1 and 10
A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

# Perform addition and subtraction
C_add = A + B
C_sub = A - B

# Print the matrices and the results
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("A + B:")
print(C_add)
print("A - B:")
print(C_sub)


Matrix A:
[[8 3 8]
 [5 1 4]
 [3 4 7]]
Matrix B:
[[ 7  9 10]
 [ 4  7  8]
 [10  8  7]]
A + B:
[[15 12 18]
 [ 9  8 12]
 [13 12 14]]
A - B:
[[ 1 -6 -2]
 [ 1 -6 -4]
 [-7 -4  0]]


In [92]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

import numpy as np

# Create matrix C of shape (3, 2) with random integers between 1 and 10
C = np.random.randint(1, 11, size=(3, 2))

# Create matrix D of shape (2, 4) with random integers between 1 and 10
D = np.random.randint(1, 11, size=(2, 4))

# Perform matrix multiplication
result = np.dot(C, D)

# Print the matrices and the result
print("Matrix C:")
print(C)
print("Matrix D:")
print(D)
print("C * D (Matrix multiplication result):")
print(result)



Matrix C:
[[3 3]
 [6 3]
 [1 6]]
Matrix D:
[[ 1  7  2  5]
 [ 9  7 10  2]]
C * D (Matrix multiplication result):
[[30 42 36 21]
 [33 63 42 36]
 [55 49 62 17]]


In [93]:
# 83. Create a matrix `E` and find its transpose.

import numpy as np

# Create a matrix E of shape (3, 3) with random integers between 1 and 10
E = np.random.randint(1, 11, size=(3, 3))

# Find the transpose of E
E_transpose = E.T

# Print the matrix and its transpose
print("Matrix E:")
print(E)
print("Transpose of E:")
print(E_transpose)


Matrix E:
[[10  9  5]
 [ 9  5  6]
 [ 5  2  3]]
Transpose of E:
[[10  9  5]
 [ 9  5  2]
 [ 5  6  3]]


In [94]:
# 84. Generate a square matrix `F` and compute its determinant.

import numpy as np

# Create a square matrix F of shape (3, 3) with random integers between 1 and 10
F = np.random.randint(1, 11, size=(3, 3))

# Compute the determinant of F
determinant = np.linalg.det(F)

# Print the matrix and its determinant
print("Matrix F:")
print(F)
print("Determinant of F:")
print(determinant)


Matrix F:
[[ 8  3  4]
 [ 7  5 10]
 [ 8 10  6]]
Determinant of F:
-325.9999999999997


In [95]:
# 85. Create a square matrix `G` and find its inverse.

import numpy as np

# Create a square matrix G of shape (3, 3) with random integers between 1 and 10
G = np.random.randint(1, 11, size=(3, 3))

# Compute the inverse of G
try:
    G_inverse = np.linalg.inv(G)
    print("Matrix G:")
    print(G)
    print("Inverse of G:")
    print(G_inverse)
except np.linalg.LinAlgError:
    print("Matrix G is singular and does not have an inverse.")


Matrix G:
[[ 7  5 10]
 [ 4  9  8]
 [ 7  5  9]]
Inverse of G:
[[-0.95348837 -0.11627907  1.1627907 ]
 [-0.46511628  0.1627907   0.37209302]
 [ 1.         -0.         -1.        ]]
